_base_: '../_base_/global_configs.yml'

batch_size: 24
iters: 13950

model:
  type: VisionTransformer
  activation: softmax
  classifier: seg
  decoder_channels: [256, 128, 64, 16]
  hidden_size: 768
  n_skip: 3
  patch_size: 16
  patches_grid: [14, 14]
  patches_size: [16, 16]
  pretrained_path: ./data/R50+ViT-B_16.npz
  representation_size: None
  resnet_num_layers: [3, 4, 9]
  width_factor: 1
  resnet_pretrained_path: None
  skip_channels: [512, 256, 64, 16]
  attention_dropout_rate: 0.0
  dropout_rate: 0.1
  mlp_dim: 3072
  num_heads: 12
  num_layers: 12
  num_classes: 9
  img_size: 224

train_dataset:
  type: Synapse
  dataset_root: ./Synapse_image
  result_dir: ./output
  transforms:
    - type: RandomFlipRotation3D
      flip_axis: [1, 2]
      rotate_planes: [[1, 2]]
    - type: RandomRotation3D
      degrees: 20
      rotate_planes: [[1, 2]]
    - type: Resize3D
      size: [1 ,224, 224]
  mode: train
  num_classes: 9

val_dataset:
  type: Synapse
  dataset_root: ./Synapse_image
  result_dir: ./output
  num_classes: 9
  transforms:
    - type: Resize3D
      size: [1 ,224, 224]
  mode: test

test_dataset:
  type: Synapse
  dataset_root: ./Synapse_image
  result_dir: ./output
  num_classes: 9
  transforms:
    - type: Resize3D
      size: [1 ,224, 224]
  mode: test



optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 1.0e-4

lr_scheduler:
  type: PolynomialDecay
  decay_steps: 13950
  learning_rate: 0.01
  end_lr: 0
  power: 0.9

loss:
  types:
    - type: MixedLoss
      losses:
        - type: CrossEntropyLoss
          weight: Null
        - type: DiceLoss
      coef: [1, 1]
  coef: [1]
